server:
  port: 8082
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  devtools:
    restart:
      enabled: false

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB


logging:
  #  file:
  #    name: ${LOG_PATH}/log/test.log
  #    max-history: 7
  #    max-size: 10MB
  level:
    com.douzone.server: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwtSecret: ${JWT_SECRET}
jwtMs: ${JWT_MS}

jwt:
  secret-key: ${}
  header:
    access: ${}
    refresh: ${}
  type:
    access: ${}
    refresh: ${}
  time:
    access: ${}
    refresh: ${}

user:
  url:
    client: ${}
    logout: ${}
  role:
    employee: ${}
    admin: ${}
    permit-all: ${}
  cors:
    method: ${}
    header: ${}
    pattern: ${}
    source-pattern: ${}
