server:
  port: 8082
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    show-sql: true
  devtools:
    restart:
      enabled: false

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB


logging:
  #  file:
  #    name: ${LOG_PATH}/log/test.log
  #    max-history: 7
  #    max-size: 10MB
  level:
    com.douzone.server: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwtSecret: ${JWT_SECRET}
jwtMs: ${JWT_MS}

jwt:
  secret-key: ${SECRET_KEY}
  header:
    access: ${HEADER_KEY_ACCESS}
    refresh: ${HEADER_KEY_REFRESH}
  type:
    access: ${SECRET_TYPE_ACCESS}
    refresh: ${SECRET_TYPE_REFRESH}
  time:
    access: ${SECRET_TIME_ACCESS}
    refresh: ${SECRET_TIME_REFRESH}

user:
  url:
    client: ${CLIENT_URL}
    logout: ${LOGOUT_URL}
    admin: ${ADMIN_URL}
    employee: ${EMPLOYEE_URL}
  role:
    admin: ${ROLE_ADMIN}
    employee: ${ROLE_EMPLOYEE}
  permit-all: ${PERMIT_ALL}
  session-id: ${SESSION_ID}
  cors:
    method: ${CORS_METHOD}
    header: ${CORS_HEADER}
    pattern: ${CORS_PATTERN}
    source-pattern: ${SOURCE_PATTERN}
