server:
  port: 8082
spring:
  profiles:
    active: local
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://team4-database.cwmjuw9z0gli.ap-northeast-2.rds.amazonaws.com:3306/DevDB?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: qwer1234!!
  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
  devtools:
    restart:
      enabled: false
  jackson:
    property-naming-strategy: SNAKE_CASE

servlet:
  multipart:
    max-file-size: 10MB
    max-request-size: 10MB


logging:
  #  file:
  #    name: ${LOG_PATH}/log/test.log
  #    max-history: 7
  #    max-size: 10MB
  level:
    com.douzone.server: debug
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

jwt:
  header:
    access: Authorization
    refresh: RefreshToken
  time:
    access: 1800
    refresh: 604800
  secret:
    key: NeohagoNahagoWehago

user:
  url:
    client: http://localhost:3000
    logout: /logout
    admin: /admin
    employee: /emp
  role:
    admin: ROLE_ADMIN
    employee: ROLE_EMPLOYEE
  permit:
    all: '/**'
  session:
    id: 'JSESSIONID'
  cors:
    method: '*'
    header: '*'
    pattern: '*'
    source:
      pattern: '/**'